### ISSUE TITLE
Add BunnyCDN support

### ISSUE THREAD

**Issue by DTP2** [SARAVANA1501/plugin-TrackerJsCdnSync#4]
Also, please for less tech-savvy users like myself, make it easy to set up!

**Comment by SARAVANA1501** [comment]
I am doing research on bunny CDN, meanwhile can provide any example on simplifying setup?

**Comment by DTP2** [comment]
Thank you for your reply and for adding this to the milestone. 

I was reading how to add the currently supported CDN and as a not so techy person, setting this up looks quite complex. It would be easiest if I just had to write down the CDN url somewhere in the plugin and then it works.

**Comment by SARAVANA1501** [comment]
```
[TrackerJsCdnSync]
type = "bunny-cdn"
storageZoneName = "<Replace with your zone name>" <!--Example: test-bunny-name-->
apiAccessKey = "<Replace with your api key>" <!--Password from FTP & API Access page-->
storageZoneRegion = "<Replace with zone region>" <!--First two letter of domain name from FTP & API Access, example:de,sg-->
```
Added support for bunny CDN, you can configure your Matomo with above snippet

**Comment by DTP2** [comment]
Dear sir,

Can you please tell me where to paste this code?

**Comment by SARAVANA1501** [comment]
You have to paste this snippet into your config.ini.php with proper value.

**Comment by SARAVANA1501** [comment]
Are you using Matomo cloud or on-premise version?
